export const endpoints = {
  profile: "/api/v1/profile",
  projects: "/api/v1/projects",
  featuredProjects: "/api/v1/projects/featured",
  project: (slug: string) => `/api/v1/projects/${slug}`,
  skills: "/api/v1/skills",
  experience: "/api/v1/experience",
  blogPosts: "/api/v1/blog/posts",
  blogPost: (slug: string) => `/api/v1/blog/posts/${slug}`,
  blogCategories: "/api/v1/blog/categories",
  contact: "/api/v1/contact",
  testimonials: "/api/v1/testimonials",
  auth: {
    login: "/api/v1/auth/login",
    refresh: "/api/v1/auth/refresh",
    logout: "/api/v1/auth/logout",
    me: "/api/v1/auth/me",
  },
  admin: {
    dashboard: "/api/v1/admin/dashboard",
    projects: "/api/v1/admin/projects",
    project: (id: string) => `/api/v1/admin/projects/${id}`,
    skills: "/api/v1/admin/skills",
    skill: (id: string) => `/api/v1/admin/skills/${id}`,
    experience: "/api/v1/admin/experience",
    experienceItem: (id: string) => `/api/v1/admin/experience/${id}`,
    blogPosts: "/api/v1/admin/blog/posts",
    blogPost: (id: string) => `/api/v1/admin/blog/posts/${id}`,
    messages: "/api/v1/admin/messages",
    message: (id: string) => `/api/v1/admin/messages/${id}`,
    settings: "/api/v1/admin/settings",
  },
  uploads: "/api/v1/uploads",
} as const;
